apiVersion: v1
kind: Pod
metadata:
  name: portal-app-database
  labels:
    app: portal-app-database
spec:
  containers:
    - name: portal-app-database
      image: kosaraju333/portal-app-backend:V1
      ports:
        - containerPort: 5432
