version: 0.0
os: linux
# files:
#   - source: Config/config.txt
#     destination: /webapps/Config
#   - source: source
#     destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: scripts/install-portal-app.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start-portal-app.sh
      timeout: 180
  # ValidateService:
  #   - location: Scripts/MonitorService.sh
  #     timeout: 3600
  #     runas: codedeployuser


  
