apiVersion: v1
kind: Service
metadata:
  name: portal-app-frontend-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: portal-app-frontend
  ports:
    # Below Port Number is a service port number
    - port: 3000
      # Below targetPort is a Container Port number 
      targetPort: 3000