apiVersion: v1
kind: Service
metadata:
  name: portal-app-frontend-nodeport-service
spec:
  type: NodePort
  selector:
    app: portal-app-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
