name: Artifact Push

on:
 workflow_call:

jobs:
  artifact-push:
    runs-on: ubuntu-latest
    steps:
    # ### Uploading Artifact to Nexus
    #   - name: Upload to Nexus
    #     run: |
    #       curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
    #       --upload-file app-Frontend/portal-app-$DATE.tar.gz \
    #       https://nexus.spontansolutions.com/repository/portal-app-artifacts/portal-app-$DATE.tar.gz

    ### Uploading Artifact to S3
      - name: Uploading Artifact to S3 Bucket
        run: |
          cd app-Frontend
          aws s3 cp portal-app-$DATE.tar.gz s3://portal-app-spontansolutions/github-actions/
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
