name: Build

on:
 workflow_call:
  secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    ### Downloading portal-app.js
    steps:
      - name: Downloading portal-app.js from AWS
        run: |
          ls
          aws s3 cp s3://portal-spontansolutions/secrets/portal-app.js app-Frontend/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


    ### Building the app
      - name: Portal-app-Build
        run: |
          cd app-Frontend
          ls
          npm init -y
          npm i express.js body-parser knex pg nodemon

    ### Set Date Variable 
      - name: Set Date Variable
        run: echo "DATE=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV


    ### Creating Artifact
      - name: Creating Artifact
        run: |
          cd app-Frontend
          ls
          tar -czf portal-app-$DATE.tar.gz node_modules package.json public portal-app.js