name: Build Scan Push portal-app Docker Image

on:
  workflow_run:
    workflows: ["Build and Push portal-app artifact"]
    types:
      - completed

jobs:
  Docker-build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag with date
        run: echo "IMAGE_TAG=portal-app:$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

    ### Installing Docker 
      - name: Set up Docker
        uses: docker/setup-docker-action@v3

    ### Docker Login
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          cd app-Frontend
          docker build -t $IMAGE_TAG .

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy
     

      - name: Scan Docker image with Trivy
        run: |
          trivy image --severity CRITICAL,HIGH --no-progress $IMAGE_TAG

    ### Push to Docker Hub
      - name: Push Portal-app to Docker Hub
        run: |
          docker tag $IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_TAG
