name: Docker-Image-Build-Scan

on:
 workflow_call:

jobs:
  docker-image-build-scan:
    runs-on: ubuntu-latest
    steps:
      ### Build Docker Image
      - name: Build Portal-app Docker Image
        uses: docker/build-push-action@v6
        with:
          context: app-Frontend
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}

      ### Docker Image Scan
      - name: Scan local Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
          format: 'table'
          ignore-unfixed: true
          exit-code: 0
          severity: 'CRITICAL,HIGH'