name: Build and Push Docker image of  portal-app to Docker Hub

on: 
  push:
    branches:
      - "master"

jobs:
  portal-app-CI:
    name: Build and push portal-app image to DOCKER HUB
    runs-on: ubuntu-latest

    ### GIT code Checkout 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

    ### Installing Nodejs 16
      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
        #  cache: 'npm'

    ### Run Trivy FS Scan
      - name: Run Trivy FS Scan (Repository Dependencies)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH' 

    ### Configuring AWS CLI access.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    ### Downloading portal-app.js
      - name: Downloading portal-app.js from AWS
        run: |
          aws s3 cp s3://portal-spontansolutions/secrets/portal-app.js app-Frontend/

    ### Building the app
      - name: Portal-app-Build
        run: |
          cd app-Frontend
          npm init -y
          npm i express.js body-parser knex pg nodemon




