name: Pre-Build

on:
 workflow_call:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    ### Run Trivy FS Scan
      - name: Run Trivy FS Scan (Repository Dependencies)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH' 

    # ### SonarQube Scane for code analysis
    #   - name: Code analysis
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     run: |
    #       npx sonarqube-scanner \
    #       -Dsonar.projectKey=portal-app \
    #       -Dsonar.sources=app-Frontend/public \
    #       -Dsonar.host.url=https://sonarqube.spontansolutions.com/ \
    #       -Dsonar.login=$SONAR_TOKEN
    
    # ### Wait for SonarQube Analysis
    #   - name: Wait for SonarQube Analysis
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     run: |
    #       STATUS="PENDING"
    #       while [ "$STATUS" == "PENDING" ]; do
    #         sleep 20
    #         RESPONSE=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app")
    #         STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status' || echo "PENDING")
    #         echo "Waiting for SonarQube Analysis... Current Status: $STATUS"
    #       done

    # ### SonarQube Quality Gates
    #   - name: Check SonarQube Quality Gate
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     run: |
    #       STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app" | jq -r .projectStatus.status)
    #       echo $STATUS
    #       if [ "$STATUS" != "OK" ]; then
    #         echo "❌ ❌ Quality Gate Failed. Stoping deployment!! ❌ ❌ "
    #         exit 1
    #       fi
